channels:
- conda-forge
dependencies:
- python=3.10.13
- pip<=23.3
- pip:
  - mlflow==2.8.1
  - cffi==1.15.1
  - cloudpickle==2.2.1
  - dill==0.3.7
  - gmpy2==2.1.2
  - ipython==8.17.2
  - numpy==1.26.0
  - packaging==23.2
  - pandas==2.1.2
  - pydantic==2.4.2
  - pyyaml==6.0.1
  - requests==2.31.0
  - sentencepiece==0.1.99
  - torch==2.1.0
  - transformers==4.26.1
  - azureml-inference-server-http
name: mlflow-env
